spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mission?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    org.hibernate: ERROR